### ISSUE TITLE
TEXT EDITING

### ISSUE THREAD

**Issue by main-gi** [itsmattkc/LegoIslandModTool#1]
𝙷𝚘𝚠 𝚖𝚊𝚗𝚢 𝚙𝚘𝚘𝚙𝚒𝚗𝚐 𝚗𝚞𝚖𝚋𝚎𝚛𝚜?  𝙷𝚘𝚠 𝚖𝚊𝚗𝚢 𝚙𝚘𝚘𝚙𝚒𝚗𝚐 𝚗𝚞𝚖𝚋𝚎𝚛𝚜?  𝙷𝚘𝚠 𝚖𝚊𝚗𝚢 𝚙𝚘𝚘𝚙𝚒𝚗𝚐 𝚗𝚞𝚖𝚋𝚎𝚛𝚜?  𝙷𝚘𝚠 𝚖𝚊𝚗𝚢 𝚙𝚘𝚘𝚙𝚒𝚗𝚐 𝚗𝚞𝚖𝚋𝚎𝚛𝚜?  𝙷𝚘𝚠 𝚖𝚊𝚗𝚢 𝚙𝚘𝚘𝚙𝚒𝚗𝚐 𝚗𝚞𝚖𝚋𝚎𝚛𝚜?  𝙷𝚘𝚠 𝚖𝚊𝚗𝚢 𝚙𝚘𝚘𝚙𝚒𝚗𝚐 𝚗𝚞𝚖𝚋𝚎𝚛𝚜?  𝙷𝚘𝚠 𝚖𝚊𝚗𝚢 𝚙𝚘𝚘𝚙𝚒𝚗𝚐 𝚗𝚞𝚖𝚋𝚎𝚛𝚜?  𝙷𝚘𝚠 𝚖𝚊𝚗𝚢 𝚙𝚘𝚘𝚙𝚒𝚗𝚐 𝚗𝚞𝚖𝚋𝚎𝚛𝚜?  𝙷𝚘𝚠 𝚖𝚊𝚗𝚢 𝚙𝚘𝚘𝚙𝚒𝚗𝚐 𝚗𝚞𝚖𝚋𝚎𝚛𝚜?  𝙷𝚘𝚠 𝚖𝚊𝚗𝚢 𝚙𝚘𝚘𝚙𝚒𝚗𝚐 𝚗𝚞𝚖𝚋𝚎𝚛𝚜?  𝙷𝚘𝚠 𝚖𝚊𝚗𝚢 𝚙𝚘𝚘𝚙𝚒𝚗𝚐 𝚗𝚞𝚖𝚋𝚎𝚛𝚜?  𝙷𝚘𝚠 𝚖𝚊𝚗𝚢 𝚙𝚘𝚘𝚙𝚒𝚗𝚐 𝚗𝚞𝚖𝚋𝚎𝚛𝚜?  𝙷𝚘𝚠 𝚖𝚊𝚗𝚢 𝚙𝚘𝚘𝚙𝚒𝚗𝚐 𝚗𝚞𝚖𝚋𝚎𝚛𝚜?  𝙷𝚘𝚠 𝚖𝚊𝚗𝚢 𝚙𝚘𝚘𝚙𝚒𝚗𝚐 𝚗𝚞𝚖𝚋𝚎𝚛𝚜?  𝙷𝚘𝚠 𝚖𝚊𝚗𝚢 𝚙𝚘𝚘𝚙𝚒𝚗𝚐 𝚗𝚞𝚖𝚋𝚎𝚛𝚜?  𝙷𝚘𝚠 𝚖𝚊𝚗𝚢 𝚙𝚘𝚘𝚙𝚒𝚗𝚐 𝚗𝚞𝚖𝚋𝚎𝚛𝚜?

**Comment by Ephemeralic** [comment]
### **what text though????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????**

**Comment by itsmattkc** [comment]
^
